### ISSUE TITLE
How to read dir use read not readall

### ISSUE THREAD

**Issue by chutingxia** [bazil/fuse#269] opened 2020-12-23 01:13 UTC
when i do HanderReadRequest, i want to read dir ,but i only can use HandleReadDirAller, can i use HandleReader like read a file  as my dir is too large

**Comment by tv42** [comment] 2020-12-23 17:02
Stop spamming the issues. Only ReadDirAll is implemented.

**Comment by tv42** [comment] 2020-12-23 17:02
Duplicate of https://github.com/bazil/fuse/issues/58

**Closed by tv42** 2020-12-23 17:02 UTC

**Comment by chutingxia** [comment] 2020-12-24 04:17
thank you , i get it!
