### ISSUE TITLE
Broken with OSXFUSE 3.0.4

### ISSUE THREAD

**Issue by trevordixon** [bazil/fuse#103] opened 2015-07-09 04:15 UTC
Tried with the example filesystems clockfs.go and hello.go. Error:

    fork/exec /Library/Filesystems/osxfusefs.fs/Support/mount_osxfusefs: no such file or directory

There is a `/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse` and a `/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse`. Changing the paths to those avoids errors, but the filesystem doesn't actually mount. The mount directory is empty, and calling `umount` reports "not currently mounted".

**Comment by tv42** [comment] 2015-07-09 06:12
Yeah, OSXFUSE 3.x renamed a bunch of things. There's a branch, https://github.com/bazil/fuse/tree/wip-osxfuse3 that just flips all the places over to new values; that branch won't work with OSXFUSE 2.x. The real fix is to take all those locations and handle both variants. I am currently undecided on what's the best way to detect what version we're running against.

I have postponed that work for now as OSXFUSE 3.x has been very, *very* unstable for me so far. Running my unit tests has been enough to cause a hard reboot.

**Comment by fd0** [comment] 2015-08-26 11:28
Since a few days ago homebrew/cask installs OSXFUSE 3 by default, which breaks the restic integration tests on darwin... Any idea on how to proceed here?

**Comment by tv42** [comment] 2015-08-26 16:16
OSXFUSE 3.x is a beta, homebrew should definitely not be installing it at this time.

**Comment by tv42** [comment] 2015-08-26 16:20
And for the 3.x related changes, I have that waiting in a branch and I'm coordinating with the OSXFUSE maintainer on the bugs I've seen there, e.g. https://github.com/osxfuse/osxfuse/issues/224 and https://github.com/osxfuse/osxfuse/issues/229

Once there's a 3.x beta release out that passes event most of my unit tests, I'll push the changes that enable support for it. Right now, big obvious errors are better than the hangs & data corruption that happen with 3.0.4. Once 3.0.5 is out, I expect everything except invalidations to work well enough with it, and will enable the support. The code is already written.

**Comment by fd0** [comment] 2015-08-26 16:48
Indeed, homebrew-cask (which I'm using for the integration tests) installs osxfuse 3.0.4 since a day or so: https://github.com/caskroom/homebrew-cask/blob/master/Casks/osxfuse.rb#L2 :(

**Comment by fd0** [comment] 2015-08-26 17:17
The maintainer has rolled it back to 2.8.0 in https://github.com/caskroom/homebrew-cask/pull/13442 :)

**Comment by tv42** [comment] 2015-09-28 20:45
While this issue was caused by homebrew being overeager to use beta versions, osxfuse 3.x landed in bazil.org/fuse master a while ago. Commit 808be6257421d5adcad068ddf233773a9aa26a08 or later and osxfuse 3.0.6 work just fine.

**Closed by tv42** 2015-09-28 20:45 UTC
Labels: platform:osx

**Comment by fd0** [comment] 2015-09-29 18:09
Awesome, thank you!
