### ISSUE TITLE
compare c libfuse, the operater  ls directory is  inefficiency

### ISSUE THREAD

**Issue by suruonuo** [bazil/fuse#278] opened 2021-06-11 07:37 UTC
I  use following command:
time ls  /path   
there are 20000 files in path
c libfuse  is 40 times fast than go libfuse

**Comment by tv42** [comment] 2021-06-11 16:11
Duplicate of https://github.com/bazil/fuse/issues/58 most likely.

And also written in a pretty hostile tone. I don't appreciate that much.

**Closed by tv42** 2021-06-11 16:11 UTC
