### ISSUE TITLE
Versioning Please?

### ISSUE THREAD

**Issue by rucuriousyet** [bazil/fuse#190] opened 2017-10-28 04:36 UTC
I'm trying to use this library on for the first time and while I get the gist of things, the documentation (specifically the zipfs implementation example) is very much out of date with the godoc. Having to dig around and experiment because methods are not described or have altogether changed is rather frustrating...

**Comment by tv42** [comment] 2017-10-28 17:58
Versioning will happen after API stability. We're not there yet; the current API cannot provide good enough performance.

**Comment by tv42** [comment] 2017-10-28 17:58
Duplicate of #184.

**Closed by tv42** 2017-10-28 17:58 UTC
