### ISSUE TITLE
File system mysteriously unmounted soon after Init plus "short kernel write"

### ISSUE THREAD

**Issue by jacobsa** [bazil/fuse#89] opened 2015-06-05 05:33 UTC
I'm seeing a weird problem where file systems are unmounted very soon after responding to Init, even when the user doesn't request it. I can easily reproduce this in bazil.org/fuse tests. I see this only on one version of Linux (the newest one I have access to), not older ones.

Here is what I am running:

    % uname -a
    Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

This is actually a Google Compute Engine VM that I created like this:

    gcloud compute instances create ubuntu --scopes storage-full --image /ubuntu-os-cloud/ubuntu-1504-vivid-v20150422 --machine-type n1-standard-4 --project github-jacobsa-gcloud --zone asia-east1-a --boot-disk-size 500GB

I can reproduce this at commit e4fcc9a2c7567d1c42861deebeb483315d222262 with the following patch, simply sleeping for a moment after mounting:

```
diff --git a/options_test.go b/options_test.go
index c6d4af0..1c6c5a3 100644
--- a/options_test.go
+++ b/options_test.go
@@ -5,6 +5,7 @@ import (
        "runtime"
        "syscall"
        "testing"
+       "time"
 
        "bazil.org/fuse"
        "bazil.org/fuse/fs"
@@ -212,6 +213,8 @@ func TestMountOptionReadOnly(t *testing.T) {
        }
        defer mnt.Close()
 
+       time.Sleep(time.Second)
+
        // This will be prevented by kernel-level access checking when
        // ReadOnly is used.
        f, err := os.Create(mnt.Dir + "/child")
```

The test fails like this:

```
2015/06/05 05:32:08 FUSE: short kernel write: written=-1/40 error="no such file or directory" stack=
goroutine 51 [running]:
bazil.org/fuse.stack(0x0, 0x0)
        /home/jacobsa/go/src/bazil.org/fuse/debug.go:9 +0x84
bazil.org/fuse.(*Conn).respond(0xc208042840, 0xc2080874f0, 0x28)
        /home/jacobsa/go/src/bazil.org/fuse/fuse.go:937 +0x169
bazil.org/fuse.(*Header).respond(0xc208030dc0, 0xc2080874f0, 0x28)
        /home/jacobsa/go/src/bazil.org/fuse/fuse.go:219 +0x3f
bazil.org/fuse.(*InitRequest).Respond(0xc208030dc0, 0xc20800b310)
        /home/jacobsa/go/src/bazil.org/fuse/fuse.go:999 +0xab
bazil.org/fuse/fs.(*serveConn).serve(0xc2080463c0, 0x7f4e4109d130, 0xc208030dc0)
        /home/jacobsa/go/src/bazil.org/fuse/fs/serve.go:797 +0x97b
bazil.org/fuse/fs.func·001()
        /home/jacobsa/go/src/bazil.org/fuse/fs/serve.go:367 +0x78
created by bazil.org/fuse/fs.(*Server).Serve
        /home/jacobsa/go/src/bazil.org/fuse/fs/serve.go:368 +0x805

2015/06/05 05:32:10 unmount error: exit status 1: fusermount: entry for /tmp/fusetest085203965 not found in /etc/mtab
2015/06/05 05:32:10 unmount error: exit status 1: fusermount: entry for /tmp/fusetest085203965 not found in /etc/mtab
2015/06/05 05:32:10 unmount error: exit status 1: fusermount: entry for /tmp/fusetest085203965 not found in /etc/mtab
[...]
```

Any idea what is going on here?

**Comment by jacobsa** [comment] 2015-06-05 05:42
It is more finicky to reproduce this than the first time I try, where I guess I got lucky. This works reliably for me, although the short kernel write message is not always printed:

    go test -c && (for i in {1..1000}; do { echo $i; ./fuse.test --test.v || exit 1}; done) && echo OKAY

**Comment by tv42** [comment] 2015-06-05 16:27
@jacobsa What was in the log just before that debug message? Anything useful in dmesg?

The debug message itself is a leftover from hunting an unrelated bug on OSXFUSE, which should be fixed, and is only in respond not in respondData, so it won't even trigger if that kernel error comes from e.g. WriteResponse.. but what it does say is that the write to /dev/fuse got an ENOENT. Most of those code paths seem to be about aborted requests.

I left an infinite loop trying to reproduce that under kernel 3.19, let's see..

**Comment by tv42** [comment] 2015-06-05 16:56
I can reproduce the behavior. Tests *pass* still and nothing in dmesg. Did you actually ever see a test failure?

**Comment by tv42** [comment] 2015-06-05 18:28
Adding more instrumentation, I see a successful Init response getting an ENOENT. The way I read fs/fuse/dev.c:fuse_dev_do_write, errors can only result from the envelope processing, not from handling the response itself.

There may be some other paths that get ENOENT, but what I'm seeing is that responding to aborted requests causes ENOENT. But I don't really see why the InitRequest would get aborted, unless something was already unmounting the filesystem. Perhaps we have a race somewhere in the setup logic.

**Comment by tv42** [comment] 2015-06-05 19:07
Now that I know what I'm looking for, I can reproduce it even on Linux 3.13; it seems unrelated to recent kernel changes.

**Comment by jacobsa** [comment] 2015-06-05 20:49
Oh nice find! Some things:

* I think that debug message was a red herring; I almost never see it.
* Yes I agree, my reading of the kernel source is also that the request has been aborted due to the connection being shut down.
* And the connection gets shut down because the file system is unmounted (or an abort file in /sys/fs/fuse/connection is written to).
* So what the hell is unmounting the file system?

I tried to answer that last question with dtrace, but it causes my VM to freeze. :-( If you have a real machine that you can dtrace on, maybe try it? The program for Linux is [here](https://github.com/dtrace4linux/linux). I was planning on counting unmount/unmount2 syscalls by process, and maybe also tracing the functions that set the aborted and connected flags in fuse.

**Comment by jacobsa** [comment] 2015-06-08 12:31
After putting together a custom `/bin/umount` program that logged evidence, I believe I've found that systemd is the culprit. There are a ton of messages in `/var/log/syslog` that appear to confirm this: every time I mount a file system with the test, systemd unmounts it within a second or two. If the unmount fails, it retries for awhile too. (More info [here](http://unix.stackexchange.com/questions/208216/why-is-systemd-unmounting-my-fuse-file-systems-right-after-i-mount-them), in particular in the comment thread for the question.)

The syslog messages look like this:

```
Jun  8 06:39:41 ubuntu systemd[1]: Unit tmp-fusetest301566509.mount is bound to inactive unit dev-fuse.device. Stopping, too.
Jun  8 06:39:41 ubuntu systemd[1]: Unmounting /tmp/fusetest301566509...
```

Importantly, if I set an fsname so that I'm not using the default of `/dev/fuse`, the problem appears to ago away. I guess systemd feels that it owns the mounting/unmounting of devices.

Can you confirm this on your end?

**Comment by tv42** [comment] 2015-06-08 14:28
Hahaha. Wow.

I have no instances of the word "Unmounting" in my logs, even when I see the write to /dev/fuse getting an error. I have no direct evidence of an unmount happening; I do have evidence of the /dev/fuse write error.

**Comment by tv42** [comment] 2015-06-08 14:32
Oh, and the the box with the earlier 3.13 kernel I reproduced the problem with does not run systemd, which leads me to think:

The unmounting and the ENOENT response look like they're two separate things. (The systemd unmount may be *one* explanation for that ENOENT, but I'll need another, to explain everything I'm seeing.)

**Comment by tv42** [comment] 2015-06-08 15:04
Okay, going based on what I understand from the above, let's say this issue was about the systemd unmount behavior, and not really a bug in `bazil.org/fuse`.

I filed https://github.com/bazil/fuse/issues/90 to track down the ENOENT problem better.

**Closed by tv42** 2015-06-08 15:04 UTC

**Comment by jacobsa** [comment] 2015-06-08 22:23
Well yes it's systemd being rude, but it does limit the portability of your tests, which don't reliably pass on recent versions of Ubuntu. (The sleep made it easier to reproduce, but was not necessary.) And it's not just tests—I believe real file systems written with this library might be affected, too. So maybe the default behavior with regard to fsname should be updated, or the documentation should at least advise setting it?

**Comment by tv42** [comment] 2015-06-08 22:27
Please go file a bug on systemd.

I may change the defaults, but that does not change where the blame belongs.

**Comment by jacobsa** [comment] 2015-06-08 22:34
Absolutely agreed. Like I said, systemd is being rude. I'm not blaming your library, I'm just saying:

1. Any code written against the library will trip on this.
2. That includes your tests, which don't reliably pass on modern Ubuntu.

I assume these bother you, so maybe there is something more to be done in this issue.

**Comment by jacobsa** [comment] 2015-06-08 22:42
Filed a systemd bug [here](https://bugs.freedesktop.org/show_bug.cgi?id=90907).

**Comment by tv42** [comment] 2015-06-08 22:43
They bother me only on a level where systemd bothers me as a whole. I'm not really keen on adding Lennart workarounds to something as simply a user mounting a filesystem. If systemd craps on these tests, it'll most likely also crap on sshfs and just about every existing FUSE filesystem out there.

If you can show me how my code is special, I'll make it not be special. If you're trying to tell me every single pre-existing FUSE server needs to change because of systemd, I will grab popcorn.

**Comment by jacobsa** [comment] 2015-06-08 22:44
sshfs and all other fuse file systems I've used set an fsname option. The difference with these tests is that they don't.
