### ISSUE TITLE
Uid, Gid and Pid wrongly (?) set to zero in fuse.ReleaseRequest on Ubuntu

### ISSUE THREAD

**Issue by airnandez** [bazil/fuse#100] opened 2015-06-30 14:11 UTC
Hello,

while developing [clueFS](https://github.com/airnandez/cluefs) I noticed that the request passed by `bazil/fuse` to my implementation of [HandleReleaser](http://godoc.org/bazil.org/fuse/fs#HandleReleaser) interface is not filled in the same way on MacOS X and on Ubuntu.

On Ubuntu, the `Uid`, `Gid` and `Pid` fields are set to zero whereas in MacOS X those fields are set to the correct user, group and process ids who called the `close()` system call.

Here is a quick way to reproduce it using the built-in `hellofs` example:

1. Add the `Release` function below to `examples/hellofs/hello.go`:

      ```go
      func (File) Release(ctx context.Context, req *fuse.ReleaseRequest) error {
	     fmt.Printf("req=%#v\n", req)
	     return nil
      }
      ```
* Compile and run `hellofs`:

   ```bash
    $ hellofs $HOME/mnt
   ````
* In another terminal do: `cat $HOME/mnt/hello`

On Ubuntu you get:

   ```
   req=&fuse.ReleaseRequest{Header:fuse.Header{Conn:(*fuse.Conn)(0xc208052120), ID:0x12, Node:0x2, Uid:0x0, Gid:0x0, Pid:0x0, msg:(*fuse.message)(0xc20803c420)}, Dir:false, Handle:0x1, Flags:0x0, ReleaseFlags:0x0, LockOwner:0x0}
   ```

On MacOS X you get:

   ```
   req=&fuse.ReleaseRequest{Header:fuse.Header{Conn:(*fuse.Conn)(0x208350120), ID:0x9, Node:0x2, Uid:0x1f5, Gid:0x14, Pid:0xcfd2, msg:(*fuse.message)(0x20834f140)}, Dir:false, Handle:0x1, Flags:0x0, ReleaseFlags:0x0, LockOwner:0x0}
   ```

As you can see, on Ubuntu you get the fields set to zero: `Uid:0x0, Gid:0x0, Pid:0x0`.

In case it matters, here is my testing environment:

* MacOS X 10.9.5 with OSXFUSE 2.7.5
* Ubuntu 14.04 with fuse 2.9.2-4ubuntu4.14.04.1 (as shown by `dpkg -s fuse`)

Hope this helps.

**Comment by airnandez** [comment] 2015-06-30 14:42
A test on CentOS 7 with fuse-2.9.2-5.el7.x86_64 shows the same (wrong) behavior as on Ubuntu.

**Comment by tv42** [comment] 2015-07-05 19:05
This is not something a userspace FUSE library has any say over. If the Linux FUSE kernel module does not put the information there, the information will not be there; if you want the information to be there, you need to talk to the people maintaining that part of the Linux kernel. I for one would be careful to label what the Linux FUSE kernel module does as "wrong"; that is the definition of FUSE. "Nonideal", perhaps.

As for OSXFUSE, the platforms will always have small differences, and this is very much not the biggest of them.

You should not use Release for much more than decrementing refcounts. Flush and Fsync are there for a reason.

As for documenting *all* of the little weirdnesses of FUSE/OSXFUSE/FreeBSD FUSE: that is a mighty task that may happen slowly over time, but 1) I'd rather write code 2) I'm wary of giving bad advice on something I do not understand. In particular, I don't feel "May be zero." repeated over all those fields to add much signal, and I have no idea under what circumstances they may be zero. 

Along similar lines, bazil.org/fuse is but one FUSE userspace library. General FUSE documentation doesn't really belong in it, and should be shared across FUSE implementations. It's like trying to write the HTTP spec inside Go's net/http.

However, going through these issues will be a useful input for that, and I'm flagging this issue as documentation related -- but closing it; there is no code change to be done, and I don't want too many "FUSE is confusing" documentation bugs open, cluttering the actual code bugs. Right now, we can't worry about a hundred papercuts, we're still missing a limb.

I know @jacobsa has been doing work in trying to figure out FUSE odds and ends. If you guys feel up to it, we could always set up a parallel documentation-only repo; I would gladly help in that, e.g. by reading the kernel source to explain something.

**Closed by tv42** 2015-07-05 19:05 UTC

**Comment by jacobsa** [comment] 2015-07-05 22:09
I agree that ideally documentation doesn't belong in a userspace library—it should be in the fuse project itself somewhere. Unfortunately, the fuse project has completely failed to write usable documentation, especially about little issues like this.

So like @tv42 said, I have been beating my head against kernel source code and mailing list in order to document the answers questions like this that come up in my work on a fuse file system. The fruits of my labor are in [github.com/jacobsa/fuse](https://github.com/jacobsa/fuse), and more specifically [package fuseops](http://godoc.org/github.com/jacobsa/fuse/fuseops). I don't think it covers this particular question, though.

**Comment by tv42** [comment] 2015-07-05 22:40
The problem is that "the FUSE project" has historically meant the C userspace library.. and that project is very much what you'd expect when you hear it's still on SourceForge. I think my favorite tidbit is that the Doxygen API docs are still labeled experimental.

Anyway, as far as I'm concerned, "the FUSE project" is just another userspace FUSE library. I don't think *that* is the right place for documentation either. And, realistically, not wanting to make changes there is probably critical for any success.

As for the Linux kernel implementation, I don't see them wanting to document OSXFUSE weirdness.

And so on.

As far as I'm concerned, FUSE documentation really needs to sit in a location that can have all parties cooperate, in a form that e.g. OSXFUSE can easily list out its differences (where not included already). And I'm willing to work on it, it's just quite far from what's critical for me right now.

**Comment by jacobsa** [comment] 2015-07-05 23:24
Haha yeah, I was thinking the same thing about SourceForge. I actually stuck a mirror on GitHub just so I had a good target for links.

You're totally right about the ideal; I'm just doing what I can accomplish personally.

**Comment by tv42** [comment] 2015-07-05 23:57
@jacobsa And thank you for what you're doing! I do want to come back and look at all of your discoveries; I just know there's still chunks of functionality missing I want to get done first.
