### ISSUE TITLE
read dir can not use read

### ISSUE THREAD

**Issue by chutingxia** [bazil/fuse#268] opened 2020-12-22 11:45 UTC
when I do fuse.ReadRequest, I want to read dir, it only can HandleReadDirAller, can not HandleReader, as my dir is a large buffer, can i read dir use HandleReader like read a file

**Comment by tv42** [comment] 2020-12-22 17:20
Duplicate of https://github.com/bazil/fuse/issues/58

**Closed by tv42** 2020-12-22 17:20 UTC
