### ISSUE TITLE
Invalidating cache on node and all its children

### ISSUE THREAD

**Issue by Zirak** [bazil/fuse#111] opened 2015-09-15 11:31 UTC
(This is a question, not a feature request or a bug. Sorry for its length, I just have to set the field to properly explain.)

I'll have an easier time explaining through an example. There'll be a more concrete explanation after that.

Here's an example filesystem: https://gist.github.com/Zirak/63ea1d1ec580923470c7

It gives you 10 directories, aptly numbered, each containing a file named `rand`, whose contents is some random number or another. Its point is to just give you a bunch of random numbers. So far so good! Looks like it's working:

```sh
% ls mnt
0  1  2  3  4  5  6  7  8  9
% cat mnt/0/rand
5577006791947779410
% cat mnt/1/rand
8674665223082153551
```

Great! There's just one problem though: This is a completely dynamic filesystem. Two consecutive `cat`s to the same file should give different answers, but of course, they don't:

```sh
% cat mnt/0/rand
5577006791947779410
% cat mnt/0/rand
5577006791947779410
```

:(

### Concrete explanation
I'm building a filesystem ([pacman-fs](https://github.com/Zirak/pacman-fs)) which at some point in the tree is completely dynamic. Long story short, it wraps package management, so `ls /pkg/installed` for instance gives you a list of installed packages, and `cat /pkg/installed/zsh/version` for instance gives you the version of the installed zsh.

I gather the package list and all such stuff on `ls /pkg/installed`, build the child tree and initialize all the necessary structs. Happy happy world.

Problem ensues! What happens here:

```sh
% cat /pkg/installed/zsh/version
5.1.0-1
# update zsh version, one way or another, to 5.1.1-1
% cat /pkg/installed/zsh/version
5.1.0-1
```

While I initialize all the things when you access `/pkg/installed` on the 1st cat, the 2nd cat doesn't pass through any parent at all (which does make sense), causing it to display stale data. That'll happen to every operation on `/pkg/installed/zsh` until something else hits `/pkg/installed` again.

### Things I've tried
* Changing `/pkg/installed`'s mtime
* Invalidating `/pkg/installed`'s cache (`InvalidateNode`)
* Looking at fuse mount options, seeing `kernel_cache`, realising it's probably the exact opposite of what I want (is it?)

It seems that the problem is recursivity: I want absolute control over the tree starting from some point, so no operation can get by without me intervening. I can't figure out how to do that.

What am I missing? Any pointers? Maybe a link to some magical method which does exactly what I want and will make me feel very silly?

Thanks in advance!

p.s.: Awesome work on Bazil! The world has a shortage of good FUSE drivers.

**Comment by tv42** [comment] 2015-09-15 15:51
I'd say you want to set `resp.Flags |= fuse.OpenDirectIO` in your `Open` handler. That'll get you `/proc`-like pseudofile properties for that file handle; you will see every single read & write operation, with no caching. (With the obvious performance downsides, but since these are small files that should be fine.)

Beware sheared reads: if your file content flips from "foo" to "bar" two sequential reads might end up seeing "fo"+"r"; a common trick is to "freeze" the file handle to have a snapshot of the contents at the time of the open.

http://godoc.org/bazil.org/fuse#OpenResponse

I think this is what you need, so I'm closing this bug. Feel free to reopen if there's something really missing.

**Closed by tv42** 2015-09-15 15:51 UTC

**Comment by tv42** [comment] 2015-09-15 15:54
For the invalidations, you'd have to invalidate all of the nodes and/or direntries one by one; there is no recursion or anything like that there. Ignoring OSX, you might be able to invalidate just the top entry, and construct a wholly separate node for every lookup of `/pkg/installed`, with its own immutable content. That sounds wasteful, so I think my earlier comment is a better direction to go in.

**Comment by Zirak** [comment] 2015-09-15 18:59
Thanks for the reply.

I'm not sure I follow how overriding `Open` helps, perhaps I didn't precisely explain the problem: Going with the simpler example of the random number folder, the `ReadAll` of every random number file `mnt/0/rand` is called, so if the lookup was on the `ReadAll` all was well with the world.

In other words, when doing the following:

```sh
% cat mnt/0/rand # 1
% cat mnt/0/rand # 2
```

The following happens:
- First line:
  * `RandDir` (mnt/) - Lookup
  * `RandNumberDir` (0/) - Attr
  * `RandNumberDir` (0/) - Lookup
  * `StupidFile` (rand) - Attr
  * `StupidFile` (rand) - ReadAll
- Second line:
  * `StupidFile` (rand) - Attr
  * `StupidFile` (rand) - ReadAll

While it needs to behave like the first line no matter how many times it's called.

Invalidating the cache recursively is one solution I'll defer to if no better one is found.

**Comment by tv42** [comment] 2015-09-15 19:25
With `OpenDirectIO`, there's no caching of the file contents. That seems sufficient for your `/pkg/installed/zsh` to serve up-to-date content.

**Comment by Zirak** [comment] 2015-09-16 18:15
But that only applies to `Open`, and the directories along the way aren't `Open`ed. I do get called every time a file is to be read (`ReadAll`), but as far as my code is concerned, that's too late - by the time the contents are read all the lookups which should have happened didn't.

**Comment by tv42** [comment] 2015-10-19 23:26
I'm sorry, I don't understand what the problem is.

If you want `/pkg/installed/zsh` to disappear suddenly, stop showing it in `Readdir`, stop returning it from `Lookup`, and do an `InvalidateEntry`. If you want its children to have similar behavior, do similar actions for them -- the underlying mechanisms, all the way to kernel internals, have no concept of "and all its children". Also according to how UNIX filesystems behave, none of the above in any way invalidates already open handles.

Please give a singular, concrete, non-hypothetical example of what you want to see. Until that happens, I'm sorry but I just don't have enough information to help you.
